name: Docker Build and Push

on:
  workflow_call:
    outputs:
      image:
        description: 'Image name and tag published.'
        value: ${{ jobs.docker.outputs.image }}

jobs:
  docker:
    outputs:
      image: ${{ steps.set-image-name.outputs.IMAGE_NAME }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set Docker image name
      id: set-image-name
      run: |
        OWNER_AND_REPO=${{ github.repository }}
        REPO_NAME=$(echo "$OWNER_AND_REPO" | cut -d'/' -f2)
        echo "IMAGE_NAME=${{ secrets.DOCKER_HUB_USER }}/${REPO_NAME}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.set-image-name.outputs.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}
